### ISSUE TITLE
Internal speaker not working with ubuntu 20.04 

### ISSUE THREAD

**Issue by kaverappa-eb** [CO-1/asus-flow-x13-linux#13]
I have updated my kernel to Linux 5.16.0-051600-generic, yet internal speaks don't work

**Comment by X8O7** [comment]
I'm on the same Kernel on Linux Mint. If you installed the sources from here everything should work just fine, except XG Mobile graphic card

**Comment by kaverappa-eb** [comment]
@X8O7 Can you point me to the source that you mentioned.

**Comment by kaverappa-eb** [comment]
with ubuntu 22.04 LTS speak works fine
