### ISSUE TITLE
Upstream sound patch

### ISSUE THREAD

**Issue by flukejones** [CO-1/asus-flow-x13-linux#2]
Hi! Someone linked to your repo in my [discord server](https://discord.gg/xrVf5Myh) regarding the sound patch. I was wondering if you had upstreamed it or you would like some help doing so?

We have a website also - https://asus-linux.org/. And your suspend issues may be fixed by patches 0013-0018 [here](https://gitlab.com/asus-linux/fedora-kernel)

**Comment by CO-1** [comment]
Hi! I planed to upstream it (hence the /patches directory) but got swamped with work. Any help for upstreaming them would be very appreciated. Even though I forgot to add a license file the code is under GPLv2 and I agree and want them to be upstreamed.

As soon as I will have some time will try to see what causes resume reboot and if any/all the patches you mentioned fixes it.

**Comment by flukejones** [comment]
Real sorry to be late in reply. I've also been very tied up with work.

To get this upstreamed you can do: https://sjp38.github.io/post/git_email_setup/

Then:
1. `git format-patch HEAD^` (assuming the patch is last commit)
2.
 ```
[luke@fedora]$ ./scripts/get_maintainer.pl sound/pci/hda/patch_realtek.c
Jaroslav Kysela <perex@perex.cz> (maintainer:SOUND)
Takashi Iwai <tiwai@suse.com> (maintainer:SOUND,commit_signer:120/120=100%,authored:26/120=22%,added_lines:254/1134=22%,removed_lines:71/116=61%)
Kailang Yang <kailang@realtek.com> (commit_signer:17/120=14%,authored:16/120=13%,added_lines:170/1134=15%,removed_lines:15/116=13%)
Jeremy Szu <jeremy.szu@canonical.com> (commit_signer:14/120=12%,authored:14/120=12%)
Hui Wang <hui.wang@canonical.com> (commit_signer:14/120=12%,authored:13/120=11%,added_lines:99/1134=9%,removed_lines:11/116=9%)
Jian-Hong Pan <jhp@endlessos.org> (commit_signer:9/120=8%)
Chris Chiu <chris.chiu@canonical.com> (authored:7/120=6%)
Huacai Chen <chenhuacai@kernel.org> (added_lines:114/1134=10%)
PeiSen Hou <pshou@realtek.com> (added_lines:79/1134=7%)
Sami Loone <sami@loone.fi> (removed_lines:9/116=8%)
alsa-devel@alsa-project.org (moderated list:SOUND)
linux-kernel@vger.kernel.org (open list)
```
3.
```
git send-email --to=tiwai@suse.com --cc=perex@perex.cz,kailang@realtek.com,jeremy.szu@canonical.com,hui.wang@canonical.com,jhp@endlessos.org,chris.chiu@canonical.com,chenhuacai@kernel.org,pshou@realtek.com,sami@loone.fi,linux-kernel@vger.kernel.org <INSERT PATCH FILENAME>
```

It should be fairly painless.

**Comment by flukejones** [comment]
Otherwise I can do it for you but I'll have to change the `signed off by` to match my email.

**Comment by flukejones** [comment]
Okay I've not heard back from you for a while. Others are requiring this patch now so I'll upstream it - I do need to change the author and signed-off so I can do so though (very sorry).
