### ISSUE TITLE
Speaker not working ubuntu 20.04 ROG flow x13 

### ISSUE THREAD

**Issue by sumitsarkar1** [CO-1/asus-flow-x13-linux#9]
Is any onyone facing no sound problem on ASUS ROG flow x13 with ubuntu 20.04? Any solutions to no sound problem. Note: Sound with headphone and bluetooth speakers works perfectly. No sound without headphone ot bluetootth speakers. Available Alsamixer and pulseaudio hacks on the internet alreadty explored with no luck.

**Comment by X8O7** [comment]
Just follow the Readme. After installing the sources from this git repos everything except external mobile graphic works.

**Comment by CO-1** [comment]
Sound fix is included in newer upstream kernels.
If a kernel with the fix is not available to your distro take a look in this repository history for dkms sound patch. You will have to DIY but is may provide a starting point.
